### ISSUE TITLE
 It did not work.

### ISSUE THREAD

**Issue by ExoAnime** [freshstudio/Toshinou#39]
Not working. Swf changing.  The plugin is failing. 
I tried everything in Firefox and Chrome.

Swf change successful. Plugin failed.

**Comment by Mspy1** [comment]
That error you're getting is not Toshinou's problem.
If you need help join our discord channel.
We will try our best to help you.

**Comment by freshstudio** [comment]
As above. Closed.

**Comment by KilltoLiveTR** [comment]
I have this problem too.

**Comment by HaselLoyance** [comment]
0) Have Fiddler/Other proxy enabled and rules set to replace the swf files
1) Clear browser cache
2) Reload extension in extensions tab
3) Refresh the game page with Ctrl+F5 or Ctrl+R
4) If it says _UNSAFE JS_ then refresh by just pressing F5

Should work

**Comment by ExoAnime** [comment]
Add a link to the description. Many people have this problem.

Normal Google Chrome(It did not work): 63.0.3239.84 
The version of the scanner is problematic.


It works in beta-stage browser. 
Beta(65.0.3292.0)(Worked);
https://www.chromium.org/getting-involved/download-chromium

**Comment by freshstudio** [comment]
It works fine for me on Chromium 62, so it wasn’t the issue. For sure.

**Comment by tfkmaster** [comment]
Work on Chrome 63.0.3239.84 for me.
