### ISSUE TITLE
is it working????

### ISSUE THREAD

**Issue by GL4** [freshstudio/Toshinou#40]
The program is working now or not?

**Comment by freshstudio** [comment]
Check it yourself or visit the discord server.

**Comment by GL4** [comment]
i check it bro[and i download the new file]....but when i'm loging in darkorbit the program is not starting...

**Comment by freshstudio** [comment]
Show a screenshot of Chrome debug console (Ctrl+Shift+I) (console tab) and a screenshot of Fiddler settings + AutoResponder and chrome extension page.

**Comment by GL4** [comment]
http://prntscr.com/hm6i5t
http://prntscr.com/hm6iw4
http://prntscr.com/hm6k00

**Comment by freshstudio** [comment]
Try in incognito mode.
