### ISSUE TITLE
New error...

### ISSUE THREAD

**Issue by ExoAnime** [freshstudio/Toshinou#42]
What is the cause of the mistake? It's starting to come today.

https://prnt.sc/hnau9q

WebConsole;
1; WebClient.js:8 [Deprecation] Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.
get @ WebClient.js:8
2; Mixed Content: The page at 'https://int13.darkorbit.com/indexInternal.es?action=internalMapRevolution' was loaded over HTTPS, but requested an insecure plugin data 'http://eps.darkorbit.infinicast.io/crossdomain.xml'. This content should also be served over HTTPS.

**Comment by BOLT3R** [comment]
join discord for support

https://discordapp.com/invite/6awg2te

**Comment by freshstudio** [comment]
It's not an issue.
