### ISSUE TITLE
Does not work.

### ISSUE THREAD

**Issue by iki90009** [freshstudio/Toshinou#47]
Does not work.
Stops on the screen.
![Image](https://cdn1.savepice.ru/uploads/2017/12/22/68068c9fd5dffe8def32a5ba0ce0a6c3-full.jpg)

The map does not load.
Do not press the button.

**Comment by GeorgeMD** [comment]
Game was updated, bot needs to update too. For now it's offline. Join the discord server to see when it goes online. https://discordapp.com/invite/6awg2te

Close this issue.

**Comment by freshstudio** [comment]
Updated to the latest game client few days ago.
