### ISSUE TITLE
How to press the 0 key in the game?

### ISSUE THREAD

**Issue by iki90009** [freshstudio/Toshinou#48]
How to press the 0 key in the game?
(How do I send a 0 key to the game?)

(Using JS bot Toshinou)

**Comment by freshstudio** [comment]
1. Locate '0' key on your keyboard (it's between '9' and '-' keys).
2. Focus the game window.
3. Press the key.

FYI: It's not implemented yet and it's not an issue. For feature requests use our Discord server.
