### ISSUE TITLE
Dont work today xD

### ISSUE THREAD

**Issue by iTankiPvPz** [freshstudio/Toshinou#57]
Today the bot dont work i go to fidler and i see all in red, when i enter in DO.
I dont know much but thats what i see.

PD: U ARE THE BEST 👍 First time i see a guy let a awesome bot free <3

**Comment by fotis016** [comment]
Always check the discord status channel before you ask such questions...

**Comment by iTankiPvPz** [comment]
Where i can get the discord channel¿?

**Comment by freshstudio** [comment]
Can't you read README.md?
